export const students = [
  {
    id: 1,
    fullname: "John Smith",
    gender: "male",
    class: "A",
    age: 18,
  },
  {
    id: 2,
    fullname: "Emily Johnson",
    gender: "female",
    class: "B",
    age: 17,
  },
  {
    id: 3,
    fullname: "Michael Williams",
    gender: "male",
    class: "A",
    age: 16,
  },
  {
    id: 4,
    fullname: "Sarah Brown",
    gender: "female",
    class: "C",
    age: 18,
  },
  {
    id: 5,
    fullname: "David Jones",
    gender: "male",
    class: "B",
    age: 17,
  },
  {
    id: 6,
    fullname: "Jessica Davis",
    gender: "female",
    class: "A",
    age: 16,
  },
  {
    id: 7,
    fullname: "Christopher Wilson",
    gender: "male",
    class: "C",
    age: 18,
  },
  {
    id: 8,
    fullname: "Amanda Martinez",
    gender: "female",
    class: "B",
    age: 17,
  },
  {
    id: 9,
    fullname: "James Anderson",
    gender: "male",
    class: "A",
    age: 16,
  },
  {
    id: 10,
    fullname: "Olivia Taylor",
    gender: "female",
    class: "C",
    age: 18,
  },
];
